### ISSUE TITLE
Non-robust datasets and weights to download

### ISSUE THREAD

**Issue by f-amerehi** [PKU-ML/AdvNotRealFeatures#2]
Hi @Charles20021201  hope all is well.

The [link to the data](https://drive.google.com/drive/folders/11IQ9AvKV22RGffJcEyJdoiS1i1enW__0?usp=drive_link) and weights requires permission. Would you be able to grant me access to download them?
Also, I wonder if the dataset includes non-robust features similar to noise? Or similar to Ilays et al.'s paper the [non-robust dataset for download](https://github.com/MadryLab/constructed-datasets?tab=readme-ov-file) are not the full noise images.

Thanks very much.

**Comment by Charles20021201** [comment]
Hi!
(1) The Google Drive was set as private by mistake and the files are made available now.
(2) The images in the non-robust dataset are initialized with natural images (thus are not the full noise images).
All the best, Charles

**Comment by f-amerehi** [comment]
Many thanks @Charles20021201 Have a nice day!
